#!/bin/bash
# stolen from wllfaria
wallpapers_path="/home/joy/Pictures/Wallpapers/"
wallpaper_path=`find $wallpapers_path -type f | shuf -n 1`
gsettings set org.gnome.desktop.background picture-uri-dark $wallpaper_path
wal -i $wallpaper_path 
